version: "3.8"

services:
  parse-nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ./
    container_name: parse-nginx
    working_dir: /etc/nginx/
    volumes:
      - ~/.ssh:/root/.ssh
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10000:80"
    networks:
      - parse_network

  parse-backend:
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: ./
      target: local
    container_name: parse-backend
    volumes:
      - ~/.ssh:/root/.ssh
      - ./docker/php-fpm/supervisor.d/local.ini:/etc/supervisor.d/default.ini
      - .:/var/www
    env_file:
      - ./.env
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://root:root@parse-mysql:3306/local?charset=utf8"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - parse_network

#  digital-mysql:
#    image: mysql:8.0.29
#    container_name: digital-mysql
#    environment:
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: local
#    volumes:
#      - ./docker/mysql-data:/var/lib/mysql:rw
#    ports:
#      - "13000:3306"
#    networks:
#      - digital_network

networks:
  parse_network:
    name: parse_network
    driver: bridge
